import 'package:flutter/material.dart';
import '../models/finance_store.dart';
class CategoriesScreen extends StatelessWidget{
 final FinanceStore store;const CategoriesScreen({super.key,required this.store});
 static const icons=<String,IconData>{'Alimentos':Icons.shopping_basket_outlined,'Restaurantes':Icons.restaurant_outlined,'Transporte':Icons.directions_car_outlined,'Vivienda':Icons.home_outlined,'Servicios':Icons.receipt_long_outlined,'Salud':Icons.health_and_safety_outlined,'Compras':Icons.shopping_bag_outlined,'Entretenimiento':Icons.movie_outlined,'Educación':Icons.school_outlined,'Salario':Icons.payments_outlined,'Freelance':Icons.work_outline,'Otros':Icons.category_outlined};
 @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[Row(children:[Expanded(child:Text('Categorías',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:()=>_add(c),icon:const Icon(Icons.add),label:const Text('Nueva'))]),const SizedBox(height:8),const Text('Personaliza cómo organizas tus ingresos y gastos.'),const SizedBox(height:16),...store.categories.map((x)=>Card(child:ListTile(leading:CircleAvatar(child:Icon(icons[x]??Icons.label_outline)),title:Text(x),subtitle:Text(_usage(x)),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>_delete(c,x)))))]));
 String _usage(String x){final n=store.transactions.where((t)=>t.category==x).length;return n==0?'Sin movimientos':'$n movimiento${n==1?'':'s'}';}
 Future<void> _add(BuildContext c)async{final t=TextEditingController();final key=GlobalKey<FormState>();await showDialog(context:c,builder:(d)=>AlertDialog(title:const Text('Nueva categoría'),content:Form(key:key,child:TextFormField(controller:t,autofocus:true,decoration:const InputDecoration(labelText:'Nombre'),validator:(v){final x=(v??'').trim();if(x.isEmpty)return 'Escribe un nombre';if(store.categories.contains(x))return 'Esta categoría ya existe';return null;})),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancelar')),FilledButton(onPressed:()async{if(!(key.currentState?.validate()??false))return;await store.addCategory(t.text.trim());if(d.mounted)Navigator.pop(d);},child:const Text('Guardar'))]));}
 Future<void> _delete(BuildContext c,String x)async{final ok=await store.deleteCategory(x);if(!ok&&c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('“$x” está en uso y no se puede eliminar.')));}
}